import { supabase } from './supabase';

// Mock IDs generated by the SQL script for initial setup
const SHOP_ID = '22222222-2222-2222-2222-222222222222';
const PROFILE_ID = '11111111-1111-1111-1111-111111111111';

export const api = {
  // File Upload
  async uploadFile(file: File, folder: string) {
    const fileExt = file.name.split('.').pop();
    const fileName = `${Math.random().toString(36).substring(2, 15)}.${fileExt}`;
    const filePath = `${folder}/${fileName}`;
    const { error } = await supabase.storage.from('salon-assets').upload(filePath, file);
    if (error) throw error;
    const { data } = supabase.storage.from('salon-assets').getPublicUrl(filePath);
    return data.publicUrl;
  },

  // Services
  async getServices() {
    const { data, error } = await supabase.from('services').select('*').eq('shop_id', SHOP_ID).order('created_at', { ascending: false });
    if (error) throw error;
    return data;
  },
  async addService(service: any) {
    const { data, error } = await supabase.from('services').insert([{ ...service, shop_id: SHOP_ID }]).select().single();
    if (error) throw error;
    return data;
  },
  async updateService(id: string, service: any) {
    const { data, error } = await supabase.from('services').update(service).eq('id', id).select().single();
    if (error) throw error;
    return data;
  },
  async deleteService(id: string) {
    const { error } = await supabase.from('services').delete().eq('id', id);
    if (error) throw error;
  },

  // Staff
  async getStaff() {
    const { data, error } = await supabase.from('staff').select('*').eq('shop_id', SHOP_ID).order('created_at', { ascending: false });
    if (error) throw error;
    return data;
  },
  async addStaff(staff: any) {
    const { data, error } = await supabase.from('staff').insert([{ ...staff, shop_id: SHOP_ID }]).select().single();
    if (error) throw error;
    return data;
  },
  async updateStaff(id: string, staff: any) {
    const { data, error } = await supabase.from('staff').update(staff).eq('id', id).select().single();
    if (error) throw error;
    return data;
  },
  async deleteStaff(id: string) {
    const { error } = await supabase.from('staff').delete().eq('id', id);
    if (error) throw error;
  },

  // Shop Profile
  async getShop() {
    const { data, error } = await supabase.from('shops').select('*').eq('id', SHOP_ID).single();
    if (error) throw error;
    return data;
  },
  async updateShop(shop: any) {
    const { data, error } = await supabase.from('shops').update(shop).eq('id', SHOP_ID).select().single();
    if (error) throw error;
    return data;
  },

  // Owner Profile
  async getProfile() {
    const { data, error } = await supabase.from('profiles').select('*').eq('id', PROFILE_ID).single();
    if (error) throw error;
    return data;
  },
  async updateProfile(profile: any) {
    const { data, error } = await supabase.from('profiles').update(profile).eq('id', PROFILE_ID).select().single();
    if (error) throw error;
    return data;
  }
};
